### ISSUE TITLE
German Translations

### ISSUE THREAD

**Issue by eingemaischt** [KitronikLtd/pxt-kitronik-move-motor#7]
Hi,

at warpzone.ms we want to use some of the kitronik modules for kid education in our "Family Hacking" beginning from the elementary school.

Therefore, we need german translations to make it more accessible for these kids.

Could you please check and accept https://github.com/KitronikLtd/pxt-kitronik-move-motor/pull/6 ?

**Comment by KitronikLtd** [comment]
German translations have been added
